version: '2.0'

services:
    proxy:
        image: jwilder/nginx-proxy
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    spacebar:
        build: docker/php70
        image: web-framework/php70
        volumes:
          - ./spaceBar:/var/www/html
          - ./LoremIpsumIbrahBundle:/var/www/LoremIpsumIbrahBundle
        environment:
            VIRTUAL_HOST: spacebar.site.docker
            DOMAIN_NAME: spacebar.site.docker
