<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMM45im\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMM45im/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKMM45im.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKMM45im\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKMM45im\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KMM45im',
    'container.build_id' => 'edc4af08',
    'container.build_time' => 1528730916,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMM45im');
